Создание массива чисел

In [1]:
import numpy as np

a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [2]:
a[2]

33

In [4]:
a[[7,0,3,3,3,0,7]]

array([88, 11, 44, 44, 44, 11, 88])

In [5]:
a[a>50]

array([55, 66, 77, 88, 99])

In [6]:
2*a+10

array([ 32,  54,  76,  98, 120, 142, 164, 186, 208])

In [7]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
a= a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a[2][1]

9

In [12]:
b = [2, 3, 4, 5]
a*b

array([[ 0,  3,  8, 15],
       [ 8, 15, 24, 35],
       [16, 27, 40, 55]])

In [13]:
c = [[10], [20], [30]]
a+c

array([[10, 11, 12, 13],
       [24, 25, 26, 27],
       [38, 39, 40, 41]])

In [14]:
a = np.random.randint(0,15,size=(4,6))
a

array([[12, 14,  2,  7, 11, 14],
       [12, 12,  3,  1,  8,  8],
       [12,  9, 12, 10,  6,  3],
       [ 5,  8, 10,  6,  9, 13]])

In [17]:
a.min(axis=0) # минимальное значение элемента по столбцам


array([5, 8, 2, 1, 6, 3])

In [18]:
a.min(axis=1)  # минимальное значение элемента по строкам


array([2, 1, 3, 5])

In [22]:
a = np.arange(48).reshape(4, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [23]:
a[2][1][3]

31

In [24]:
a.ndim

3

In [25]:
a.shape


(4, 3, 4)

In [26]:
a.size

48

In [27]:
a.itemsize

4

In [28]:
a.itemsize*a.size

192

In [29]:
a.dtype

dtype('int32')

In [30]:
b = a/3.14
b

array([[[ 0.        ,  0.31847134,  0.63694268,  0.95541401],
        [ 1.27388535,  1.59235669,  1.91082803,  2.22929936],
        [ 2.5477707 ,  2.86624204,  3.18471338,  3.50318471]],

       [[ 3.82165605,  4.14012739,  4.45859873,  4.77707006],
        [ 5.0955414 ,  5.41401274,  5.73248408,  6.05095541],
        [ 6.36942675,  6.68789809,  7.00636943,  7.32484076]],

       [[ 7.6433121 ,  7.96178344,  8.28025478,  8.59872611],
        [ 8.91719745,  9.23566879,  9.55414013,  9.87261146],
        [10.1910828 , 10.50955414, 10.82802548, 11.14649682]],

       [[11.46496815, 11.78343949, 12.10191083, 12.42038217],
        [12.7388535 , 13.05732484, 13.37579618, 13.69426752],
        [14.01273885, 14.33121019, 14.64968153, 14.96815287]]])

In [31]:
b.dtype

dtype('float64')

In [32]:
b.size*b.itemsize

384