ДЗ


In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv('C:/Users/Administrator/25-12/class_code/web/24-H/Pottery.csv')
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  26 non-null     int64  
 1   Site        26 non-null     object 
 2   Al          26 non-null     float64
 3   Fe          26 non-null     float64
 4   Mg          26 non-null     float64
 5   Ca          26 non-null     float64
 6   Na          26 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 1.5+ KB


Первый график(*добавить пояснение*):

In [20]:
import numpy as np
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
a[2]

33

In [21]:
a[[7, 0, 3, 3, 3, 0, 7]]


array([88, 11, 44, 44, 44, 11, 88])

In [22]:
a[a > 50]


array([55, 66, 77, 88, 99])

In [23]:
2*a + 10

array([ 32,  54,  76,  98, 120, 142, 164, 186, 208])

In [24]:
np.sin(a)**2 + np.cos(a)**2


array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b=[2,3,4,5]
a*b

array([[ 0,  3,  8, 15],
       [ 8, 15, 24, 35],
       [16, 27, 40, 55]])

In [30]:
c = [[10], [20], [30]]
a + c

array([[10, 11, 12, 13],
       [24, 25, 26, 27],
       [38, 39, 40, 41]])

In [31]:
a = np.random.randint(0, 15, size=(4, 6))
a

array([[ 8, 10, 14, 14, 13, 12],
       [ 5, 11,  1,  4,  2,  8],
       [ 3,  5,  4,  9,  3,  6],
       [ 7, 13,  1,  8,  5,  8]])

In [32]:
a.min()

1

In [33]:
a.min(axis=0)


array([3, 5, 1, 4, 2, 6])

In [34]:
a.min(axis=1)


array([8, 1, 3, 1])

In [35]:
a.mean(axis=0)# Для стобцов 0, для строк 1

array([5.75, 9.75, 5.  , 8.75, 5.75, 8.5 ])

In [36]:
np.std(a, axis=1)

array([2.19215774, 3.43592135, 2.081666  , 3.60555128])

In [37]:
a = np.arange(48).reshape(4, 3, 4)

a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [38]:
a[2][1][3] # Блок, строка, столбик
a[2, 1, 3]


31

In [39]:
a.ndim

3

In [40]:
a.shape

(4, 3, 4)

In [41]:
a.size

48

In [42]:
a.itemsize

4

In [43]:
a.size*a.itemsize

192

In [44]:
a.dtype

dtype('int32')

In [45]:
b = a/3.14
b 

array([[[ 0.        ,  0.31847134,  0.63694268,  0.95541401],
        [ 1.27388535,  1.59235669,  1.91082803,  2.22929936],
        [ 2.5477707 ,  2.86624204,  3.18471338,  3.50318471]],

       [[ 3.82165605,  4.14012739,  4.45859873,  4.77707006],
        [ 5.0955414 ,  5.41401274,  5.73248408,  6.05095541],
        [ 6.36942675,  6.68789809,  7.00636943,  7.32484076]],

       [[ 7.6433121 ,  7.96178344,  8.28025478,  8.59872611],
        [ 8.91719745,  9.23566879,  9.55414013,  9.87261146],
        [10.1910828 , 10.50955414, 10.82802548, 11.14649682]],

       [[11.46496815, 11.78343949, 12.10191083, 12.42038217],
        [12.7388535 , 13.05732484, 13.37579618, 13.69426752],
        [14.01273885, 14.33121019, 14.64968153, 14.96815287]]])

In [46]:
b.dtype

dtype('float64')

In [47]:
b.size*b.itemsize

384