In [1]:
# булевые операции
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

a = np.array([1, 2, 3, 10, 20, 30])
indx = a > 5
a[indx]


array([10, 20, 30])

In [2]:
a[a > 5]


array([10, 20, 30])

In [3]:
b = np.array([1, 2, 3, 4, 5, 6])
a == b


array([ True,  True,  True, False, False, False])

In [4]:
np.greater(a, b)  # a > b


array([False, False, False,  True,  True,  True])

In [5]:
np.less(a, b)  # a < b


array([False, False, False, False, False, False])

In [6]:
np.equal(a, b)  # a == b


array([ True,  True,  True, False, False, False])

In [7]:
if (a == b):
    print('a==b')


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
c = np.array([1, 2, 3])
d = np.array([1, 2, 3])
if np.array_equal(c, d):
    print('a==b')


a==b


In [11]:
np.any(a > 50)


False

In [13]:
np.all(a > 0)


True

In [14]:
a/0


C:\TEMP\ipykernel_612\4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([inf, inf, inf, inf, inf, inf])

In [17]:
b = np.array([1, 2, np.inf])
b*0


C:\TEMP\ipykernel_612\2227460196.py:2: RuntimeWarning: invalid value encountered in multiply
  b*0


array([ 0.,  0., nan])

In [19]:
c = b * 0
c.sum()

C:\TEMP\ipykernel_612\1221415627.py:1: RuntimeWarning: invalid value encountered in multiply
  c = b * 0


nan

In [20]:
b = np.array([1, 2, np.nan, np.inf, -np.inf])
np.isinf(b)
np.isnan(b)

array([False, False,  True, False, False])

In [21]:
indx = np.isinf(b)
b[~indx]

array([ 1.,  2., nan])

In [22]:
np.isfinite(b)

array([ True,  True, False, False, False])

In [23]:
a = np.array([1+2j, 3-4j, 5])
np.iscomplex(a)

array([ True,  True, False])

In [24]:
a.dtype

dtype('complex128')

In [25]:
np.isreal(a)

array([False, False,  True])

In [26]:
X = np.array([True, False, True, False])
Y = np.array([True, True, False, False])

np.logical_and(X, Y)  # логическое И: array([ True, False, False, False])
np.logical_or(X, Y)  # логическое ИЛИ: array([False,  True, False,  True])
np.logical_not(X)  # логическое НЕ: array([False,  True, False,  True])
np.logical_xor(X, Y)  # XOR: array([ True,  True,  True,  True])


array([False,  True,  True, False])

In [27]:
a = np.array([1, 0, 2, 0])
b = np.array([3, 4, 0, 0])

np.logical_and(a,b)


array([ True, False, False, False])

PANDAS и работа с датасетами

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

anime = pd.read_csv('C:/Users\Administrator/25-12/class_code/web/24-H/anime.csv')
rating = pd.read_csv(
    'C:/Users\Administrator/25-12/class_code/web/24-H/rating.csv')
anime_modified = anime.set_index('name')


In [43]:
df = pd.DataFrame([[1,'Bob', 'Builder'], [2,'Sally', 'Baker'], [3, 'Scott', 'teacher']])
columns = ['id', 'name', 'occepation']
df2 = pd.DataFrame(df, columns=['id', 'name', 'occepation'])

df

0      1        2
0  1    Bob  Builder
1  2  Sally    Baker
2  3  Scott  teacher

In [34]:
anime_copy = anime.copy(deep=True)

In [36]:
anime_copy

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12289    4.15      211  
12290    4.28      183  
12291    4.88      219  
12292    4.98      175  
12293    5.46      142  

[12294 rows x 7 columns]

In [45]:
data = {'color': ['blue', 'green', 'yellow', 'red', 'white'],
        'object': ['ball', 'pen', 'pencil', 'paper', 'mug'],
        'price': [1.2, 1.0, 0.6, 0.9, 1.7]}
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [46]:
frame2 = pd.DataFrame(data, columns=['object', 'price'])
frame2


object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

In [49]:
frame3 = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['red', 'blue', 'yellow', 'white'],
                      columns=['ball', 'pen', 'pencil', 'paper'])
frame3

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [53]:
frame3.to_csv('colors.csv')